#!/bin/bash
# EndlessQuest E2E Smoke Test Runner
# 用法: 在 Claude Code 会话中按顺序执行以下步骤
# 依赖: chrome-devtools MCP server

set -e

BASE_URL="http://localhost:5173/EndlessQuest"
SCREENSHOT_DIR="tests/playwright/screenshots"

echo "=== Phase 0: 环境检查 ==="
echo "1. 确认 dev server 运行中..."
curl -sf "$BASE_URL/" > /dev/null || { echo "ERROR: dev server 未运行，请先执行 npm run dev"; exit 1; }
echo "   OK: dev server 正常"
mkdir -p "$SCREENSHOT_DIR"

echo ""
echo "=== 冒烟测试流程 ==="
echo "请按照 tests/playwright/smoke-test.md 中的步骤在 Claude Code 中执行。"
echo ""
echo "快速版检查命令（可复制到 Claude Code 中）："
echo ""
echo "--- 宗门总览 ---"
echo "navigate_page → $BASE_URL/"
echo "take_screenshot [fullPage: true, filePath: $SCREENSHOT_DIR/01-sect.png]"
echo "take_snapshot → 检查: 无白屏、6项导航、资源面板、方针按钮"
echo ""
echo "--- 弟子 ---"
echo "navigate_page → $BASE_URL/characters"
echo "take_screenshot [filePath: $SCREENSHOT_DIR/02-characters.png]"
echo "take_snapshot → 检查: 弟子列表、状态筛选"
echo ""
echo "--- 建筑 ---"
echo "navigate_page → $BASE_URL/buildings"
echo "take_screenshot [filePath: $SCREENSHOT_DIR/03-buildings.png]"
echo "take_snapshot → 检查: 建筑列表、协同无重复"
echo ""
echo "--- 秘境 ---"
echo "navigate_page → $BASE_URL/adventure"
echo "take_screenshot [filePath: $SCREENSHOT_DIR/04-adventure.png]"
echo "take_snapshot → 检查: 自动运转、探索记录"
echo ""
echo "--- 仓库 ---"
echo "navigate_page → $BASE_URL/vault"
echo "take_screenshot [filePath: $SCREENSHOT_DIR/05-vault.png]"
echo "take_snapshot → 检查: 物品列表"
echo ""
echo "--- 记录 ---"
echo "navigate_page → $BASE_URL/log"
echo "take_screenshot [filePath: $SCREENSHOT_DIR/06-log.png]"
echo "take_snapshot → 检查: 事件日志无英文"
echo ""
echo "--- 移动端 ---"
echo "resize_page [width: 375, height: 812]"
echo "navigate_page → $BASE_URL/"
echo "take_screenshot [filePath: $SCREENSHOT_DIR/07-mobile-home.png]"
echo "resize_page [width: 1400, height: 900]"
echo ""
echo "=== 检查完成 ==="
